default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: postgres
  user: postgres
 
 
development:
  <<: *default
  database: MiniCurso_development
 
 
test:
  <<: *default
  database: MiniCurso_test
 
 
production:
  <<: *default
  database: MiniCurso_production
  username: MiniCurso
  password: <%= ENV['EXCHANGE_DATABASE_PASSWORD'] %>